language: python

branches:
  only:
    - master

env:
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy3
  - TOX_ENV=coverage

install:
  - pip install tox
  - pip install nltk
  - pip install https://github.com/kpu/kenlm/archive/master.zip

before_script:
  - cd tests/data && ./download.sh && cd ../..

script:
  - tox -v -e $TOX_ENV
