language: python

branches:
  only:
    - master

env:
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=coverage

install:
  - pip install .
  - pip install -r requirements.txt
  - pip install tox

script:
  - tox -v -e $TOX_ENV
