language: python

python: 3.5

sudo: false

branches:
  only:
    - master

env:
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=coverage

install:
  - pip install nltk>=3.1
  - pip install tox>=2.2

before_script:
  - cd tests/data && ./download.sh && cd ../..
  - cd tests/data && python -m download && cd ../..

script: tox -v -e $TOX_ENV
