language: python

branches:
  only:
    - master

env:
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=coverage

install:
  - pip install nltk
  - pip install --upgrade tox

before_script:
  - cd tests/data && ./download.sh && cd ../..
  - cd tests/data && python -m download && cd ../..

script:
  - tox -v -e $TOX_ENV
